# Generated by Django 4.2.23 on 2025-09-03 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=4, verbose_name='Номер')),
                ('size', models.CharField(choices=[('small', 'Базовый'), ('medium', 'Классический'), ('large', 'Расширенный')], max_length=6, verbose_name='Размер')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Почта')),
            ],
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('discount_percentage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Скидка в %')),
                ('start_date', models.DateField(verbose_name='Начало')),
                ('end_date', models.DateField(verbose_name='Окончание')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('cell_size', models.CharField(choices=[('small', 'Базовый'), ('medium', 'Классический'), ('large', 'Расширенный')], max_length=6, verbose_name='Размер ячейки')),
                ('duration', models.IntegerField(verbose_name='Длительность')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rental_duration', models.IntegerField(verbose_name='Длительность')),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость')),
                ('rental_start_date', models.DateField(verbose_name='Начало')),
                ('rental_end_date', models.DateField(verbose_name='Окончание')),
                ('content_description', models.TextField(verbose_name='Перепись содержимого')),
                ('cell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.cell')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.client')),
                ('promotion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.promotion')),
                ('tariff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.tariff')),
            ],
        ),
    ]
