# Generated by Django 4.2.23 on 2025-09-04 14:47

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлено')),
                ('number', models.CharField(max_length=4, unique=True, validators=[django.core.validators.RegexValidator(regex='^[A-Z]{2}\\d{2}$')], verbose_name='Номер')),
                ('size', models.CharField(choices=[('small', 'Базовый'), ('medium', 'Классический'), ('large', 'Расширенный')], max_length=6, verbose_name='Размер')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
