# Generated by Django 4.2.23 on 2025-10-16 14:23

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cell',
            name='number',
            field=models.CharField(help_text='Формат: ZZ00', max_length=4, unique=True, validators=[django.core.validators.RegexValidator(message='Несоответствие формата номера', regex='^[A-Z]{2}\\d{2}$')], verbose_name='Номер'),
        ),
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлено')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('cell_size', models.CharField(choices=[('small', 'Базовый'), ('medium', 'Классический'), ('large', 'Расширенный')], max_length=6, verbose_name='Размер ячейки')),
                ('duration', models.PositiveIntegerField(verbose_name='Длительность (дней)')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
