# Generated by Django 4.2.23 on 2025-09-03 13:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_alter_order_client_delete_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cell',
            name='number',
            field=models.CharField(max_length=4, unique=True, validators=[django.core.validators.RegexValidator(regex='^[A-Z]{2}\\d{2}$')], verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='order',
            name='rental_duration',
            field=models.PositiveIntegerField(verbose_name='Длительность'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=4, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='Скидка в долях'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='duration',
            field=models.PositiveIntegerField(verbose_name='Длительность'),
        ),
    ]
