# Generated by Django 4.2.23 on 2025-10-21 07:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data', '0003_alter_cell_author_alter_tariff_author_promotion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='end_date',
            field=models.DateField(help_text='Формат: yyyy-mm-dd', verbose_name='Окончание'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='start_date',
            field=models.DateField(help_text='Формат: yyyy-mm-dd', verbose_name='Начало'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rental_duration', models.PositiveIntegerField(verbose_name='Длительность (дней)')),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость')),
                ('rental_start_date', models.DateField(help_text='Формат: yyyy-mm-dd', verbose_name='Начало аренды')),
                ('rental_end_date', models.DateField(help_text='Формат: yyyy-mm-dd', verbose_name='Окончание аренды')),
                ('content_description', models.TextField(verbose_name='Описание содержимого')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('active', 'Активен'), ('completed', 'Завершен'), ('cancelled', 'Отменен')], default='pending', max_length=10, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('cell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.cell')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('promotion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.promotion')),
                ('tariff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.tariff')),
            ],
        ),
    ]
