# Generated by Django 4.2.23 on 2025-10-21 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_alter_promotion_end_date_alter_promotion_start_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='order',
            name='updated_at',
        ),
    ]
